-- Run this once in your Supabase project → SQL Editor.
-- Community posts table, hardened so the public anon key can ONLY:
--   • read posts
--   • insert a (user_name, content) post
--   • toggle likes (likes / liked_by columns)
-- It CANNOT edit/overwrite other people's content, set arbitrary ids, or delete.
--
-- NOTE: this version uses a UUID primary key generated by the database.
-- If you previously created community_posts with a BIGINT id, drop it first
-- (DROP TABLE community_posts CASCADE;) — the app no longer sends ids.

CREATE TABLE IF NOT EXISTS community_posts (
  id         UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_name  TEXT        NOT NULL CHECK (char_length(user_name) BETWEEN 1 AND 40),
  content    TEXT        NOT NULL CHECK (char_length(content)   BETWEEN 1 AND 500),
  likes      INT         NOT NULL DEFAULT 0,
  liked_by   TEXT[]      NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ── Row Level Security ──
ALTER TABLE community_posts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public read posts"   ON community_posts;
DROP POLICY IF EXISTS "Public insert posts" ON community_posts;
DROP POLICY IF EXISTS "Public update likes" ON community_posts;

CREATE POLICY "Public read posts"
  ON community_posts FOR SELECT USING (true);

CREATE POLICY "Public insert posts"
  ON community_posts FOR INSERT WITH CHECK (true);

CREATE POLICY "Public update likes"
  ON community_posts FOR UPDATE USING (true) WITH CHECK (true);

-- ── Column-level privileges (the real guardrail) ──
-- RLS is row-level; column restrictions come from GRANTs. This is what stops a
-- malicious client from rewriting `content` or forging `id`/`created_at`.
REVOKE ALL ON community_posts FROM anon;
GRANT SELECT                         ON community_posts TO anon;
GRANT INSERT (user_name, content)    ON community_posts TO anon;
GRANT UPDATE (likes, liked_by)       ON community_posts TO anon;

-- Index for fast ordering
CREATE INDEX IF NOT EXISTS community_posts_created_at_idx
  ON community_posts (created_at DESC);

-- ── Keep only the newest 200 posts ──
-- SECURITY DEFINER so the trim can DELETE even though `anon` has no delete grant.
CREATE OR REPLACE FUNCTION trim_community_posts()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  DELETE FROM community_posts
  WHERE id IN (
    SELECT id FROM community_posts
    ORDER BY created_at DESC
    OFFSET 200
  );
  RETURN NULL;
END;
$$;

DROP TRIGGER IF EXISTS trim_posts_trigger ON community_posts;
CREATE TRIGGER trim_posts_trigger
  AFTER INSERT ON community_posts
  EXECUTE FUNCTION trim_community_posts();
